Style/Lambda:
  EnforcedStyle: literal

Style/MutableConstant:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Layout/FirstHashElementIndentation:
  EnforcedStyle: align_braces

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Metrics/MethodLength:
  Max: 25

Metrics/ParameterLists:
  Enabled: false

Metrics/LineLength:
  Max: 120
  IgnoredPatterns: ["^ *#"]

Metrics/ClassLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
